### ISSUE TITLE
It is possible to calculate version in compile time?

### ISSUE THREAD

**Issue by denizzzka** [Abscissa/gen-package-version#1]
It is possible to calculate version in compile time?
Ie, without "dub run gen-package-version -- your.package.name --src=path/to/src" calling

**Comment by Abscissa** [comment]
Not entirely sure what you mean, but D's CTFE (by design) isn't able to do general I/O, so you wouldn't be able to invoke "git describe" (which is how gen-package-version gets the version number) from D code during compile time.

**Comment by denizzzka** [comment]
I meant it.
